// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xbU4E0EAornob5fS9yDWylpNW29mS3M',
    appId: '1:71948232896:web:9c8ec4c14d6187d6972525',
    messagingSenderId: '71948232896',
    projectId: 'tourvn-app',
    authDomain: 'tourvn-app.firebaseapp.com',
    storageBucket: 'tourvn-app.firebasestorage.app',
    measurementId: 'G-SQ577KL3GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEp5aqt5VgRMG8-zvfTtXZ5Q22y9u57E',
    appId: '1:71948232896:android:236b4f7a396aaad2972525',
    messagingSenderId: '71948232896',
    projectId: 'tourvn-app',
    storageBucket: 'tourvn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYV1Yy9MQlbe1oUVnCiP92ykLQceHKXRY',
    appId: '1:71948232896:ios:2bf36e983155760f972525',
    messagingSenderId: '71948232896',
    projectId: 'tourvn-app',
    storageBucket: 'tourvn-app.firebasestorage.app',
    androidClientId: '71948232896-m9bbrs6t2f1n1bfqp2vmmk07ifnbctfv.apps.googleusercontent.com',
    iosClientId: '71948232896-u1rljbkmsd5qs6d7dq9g8dffv68uh7ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourvnApp',
  );

}